joint_dim: 1024  # 128

image:
  cls: i2t.model.ModalityEncoder
  args:
    output_dim: ${model.joint_dim}
    normalize: True
    encoder:
      # cls: i2t.model.ImageModel
      cls: i2t.model.ModifiedResNet
      args:
        # encoder_name: resnet50
        # weights: imagenet
        layers: [3, 4, 6, 3]
        output_dim: ${model.joint_dim}
        heads: 32
        input_resolution: 224
        width: 64

text:
  cls: i2t.model.ModalityEncoder
  args:
    output_dim: ${model.joint_dim}
    normalize: True
    encoder:
      # cls: i2t.model.TextModel
      cls: i2t.model.TextEncoder
      args:
        # hidden_size: 200
        # hidden_layers: 5
        embed_dim: ${model.joint_dim}
        context_length: 49
        transformer_heads: 8
        transformer_layers: 12
